In [19]:
from pathlib import Path
import pandas as pd

results_path = Path().resolve().parent / "experiments"
models = [
    "Qwen3-8B_nowait",
    "Qwen3-8B_baseline",
]

datasets = ["math-500", "amc", "aime-250", "gsm8k"] #"gsm8k", "olympiad", "amc", "aime-250", "amc"

rows = []
for model in models:
    model_dir = results_path / model
    for dataset in datasets:
        parquet_file = model_dir / f"{dataset}_results.parquet"
        if not parquet_file.exists():
            continue
        df = pd.read_parquet(parquet_file)
        total = len(df)
        correct = df["is_correct"].sum()
        accuracy = correct / total if total > 0 else 0.0
        avg_tokens = df["token_count"].mean()
        rows.append({
            "model": model,
            "dataset": dataset,
            "accuracy": accuracy,
            "num_correct": correct,
            "num_total": total,
            "avg_tokens": avg_tokens,
        })

summary = pd.DataFrame(rows)
summary

               model   dataset  accuracy  num_correct  num_total    avg_tokens
0    Qwen3-8B_nowait  math-500  0.889780          444        499   3962.032064
1    Qwen3-8B_nowait       amc  0.950000           38         40   6506.375000
2    Qwen3-8B_nowait  aime-250  0.756000          189        250  10270.148000
3    Qwen3-8B_nowait     gsm8k  0.944655         1246       1319   1184.338135
4  Qwen3-8B_baseline  math-500  0.895792          447        499   5491.406814
5  Qwen3-8B_baseline       amc  0.950000           38         40   8699.475000

In [20]:
from pathlib import Path
import pandas as pd
from eval_pipeline import is_equiv
model_deepseek = "DeepSeek-R1-Distill-Qwen-1"
model_qwen = "Qwen3-8B_baseline"
model_qwen_nowait = "Qwen3-8B_nowait"

df_qwen_math = pd.read_parquet(Path().resolve().parent / "experiments" / model_qwen_nowait / "gsm8k_results.parquet")
print("Accuracy", df_qwen_math["is_correct"].mean())
incorrect = df_qwen_math[df_qwen_math["is_correct"] == False].copy()
print("Number of incorrect answers:", len(incorrect))

Accuracy 0.9446550416982562
Number of incorrect answers: 73

In [21]:
incorrect.head(55)

,unique_id,prompt,solution,generated,expected_value,generated_value,token_count,is_correct
62,13235-gsm8k,<|im_start|>user\nIf Marcy works for the same ...,First find how many years Marcy works after 20...,"<think>\nOkay, let's try to figure out Marcy's...",25000,1875,4439,False
93,13266-gsm8k,<|im_start|>user\nLee used to be able to run t...,If Lee runs the 400-meter hurdles in 38 second...,"<think>\nOkay, let's try to figure out this pr...",36,\dfrac{400}{11},2259,False
100,13273-gsm8k,<|im_start|>user\nJerome had 4 friends who cam...,The second friend pressed on the doorbell 1/4 ...,"<think>\nOkay, let's try to figure out how许多 t...",175,705,1485,False
119,13292-gsm8k,<|im_start|>user\nAdrien's total salary was 30...,Since Adrien was earning $40000 four years ago...,"<think>\nOkay, let's try to figure out this sa...",95200,99076.92,5254,False
137,13310-gsm8k,<|im_start|>user\nRory orders 2 subs for $7.50...,2 subs are $7.50 each so that’s 2*7.50 = $<<2*...,"<think>\nOkay, let's see. Rory is ordering som...",29,29.00,1138,False
146,13319-gsm8k,<|im_start|>user\nJohnny is picking up the toy...,"The first set had 500 pieces, and the second s...","<think>\nOkay, let's see. So, the problem is a...","2,125",2125,2131,False
147,13320-gsm8k,<|im_start|>user\nDebra is monitoring a beehiv...,"Debra first sees 30 bees leave the hive, then ...","<think>\nOkay, let me try to figure out this b...",75,15,2487,False
184,13357-gsm8k,<|im_start|>user\nJerry is rolling a six-sided...,There are 3 numbers greater than 3 on the dice...,"<think>\nOkay, so Jerry is rolling a six-sided...",25,100,2007,False
187,13360-gsm8k,<|im_start|>user\nMandy owes Benedict $100. Th...,The monthly interest is $100 x 2/100 = $<<100*...,"<think>\nOkay, let's see. Mandy owes Benedict ...",106,106.12,2522,False
201,13374-gsm8k,<|im_start|>user\nJohn wins an award at work. ...,"He makes 2000*52=$<<2000*52=104000>>104,000 a ...","<think>\nOkay, let's see. So, the problem is a...","114,200",114200,1504,False
230,13403-gsm8k,<|im_start|>user\nMark buys a fleet of 12 cars...,The cars cost 20000*12=$<<20000*12=240000>>240...,"<think>\nOkay, let's see. Mark buys 12 cars fo...","276,000",276000,917,False
240,13413-gsm8k,<|im_start|>user\nJames has 6 more candies tha...,Robert has 54/2 = <<54/2=27>>27 candies.\nJame...,"<think>\nOkay, let's see. So the problem is ab...",21,"<think>\nOkay, let's see. So the problem is ab...",31942,False
241,13414-gsm8k,<|im_start|>user\nDolly has two books. Pandora...,There are 2 + 1 = <<2+1=3>>3 books in total.\n...,"<think>\nOkay, let's try to figure out this pr...",6,3,2485,False
249,13422-gsm8k,"<|im_start|>user\nOn Monday, Sue ate 4 times a...",Sue’s Monday cookie intake is 4*5 = <<4*5=20>>...,"<think>\nOkay, let's try to figure out how to ...","5,600",5600,1157,False
258,13431-gsm8k,<|im_start|>user\nNancy is returning her overd...,First multiply the late fee per book by the nu...,"<think>\nOkay, let me try to figure out how mu...",6,6.00,888,False
304,13477-gsm8k,<|im_start|>user\nWatson works a 10-hour shift...,"In a day, Watson makes 10 * 10 = $<<10*10=100>...","<think>\nOkay, let's see. I need to figure out...",3200,4800,3524,False
306,13479-gsm8k,<|im_start|>user\nA bakery produces 60 loaves ...,60 x 2/3 = <<60*2/3=40>>40 loaves of bread are...,"<think>\nOkay, let's see. The bakery makes 60 ...",10,5,878,False
340,13513-gsm8k,<|im_start|>user\nJosh decides to take up jugg...,Josh starts with 3 balls and adds 1 ball each ...,"<think>\nOkay, let's try to figure out how许多 b...",4,3,1485,False
353,13526-gsm8k,<|im_start|>user\nJohn decides to do several a...,He spent 6/2=<<6/2=3>>3 hours swimming\nHe spe...,"<think>\nOkay, let's try to figure out how muc...",20,8,6688,False
357,13530-gsm8k,<|im_start|>user\nMorgan's dad said that she h...,The go karts will cost $20 per person because ...,"<think>\nOkay, let's see. Morgan has a $90 bud...",2,12,1087,False
368,13541-gsm8k,"<|im_start|>user\nAfter scoring 14 points, Eri...",Erin now has three times more points than Sara...,"<think>\nOkay, let's try to figure out this pr...",18,10,838,False
380,13553-gsm8k,"<|im_start|>user\nKaran borrowed $3,650 for fi...","Karan's interest is $3,650 × 0.1 = $<<3650*0.1...","<think>\nOkay, so Karan borrowed $3,650 for fi...",803,760.42,3473,False
403,13576-gsm8k,<|im_start|>user\nMel uses a 900-watt air cond...,An air conditioner uses 900 x 8 = <<900*8=7200...,"<think>\nOkay, let's see. Mel uses a 900-watt ...",81,135,1711,False
406,13579-gsm8k,"<|im_start|>user\nAt Allan's house, there is t...","Before buying any corn and cannoli, Allan had ...","<think>\nOkay, let's see. So the problem is ab...",200,240,1924,False
423,13596-gsm8k,<|im_start|>user\nCole wanted to buy new jeans...,Cole saved $6 x 1/3 = $<<6*1/3=2>>2 on the jog...,"<think>\nOkay, let's try to figure out this pr...",8,6,4637,False
454,13627-gsm8k,<|im_start|>user\nMarin and his neighbor Nancy...,"In one day, Marin and Nancy eat 4 + 1 = <<4+1=...","<think>\nOkay, so the problem says that Marin ...",150,240,837,False
505,13678-gsm8k,<|im_start|>user\nFrederick is making popsicle...,He can buy six 2 x 4's because 24 / 4 = <<24/4...,"<think>\nOkay, let's see. Frederick wants to m...","1,600",1600,1863,False
539,13712-gsm8k,<|im_start|>user\nMy wife wants to evenly spli...,"If the total bill is $50, the total tip of 20%...","<think>\nOkay, let's see. My wife wants to spl...",35,30,459,False
590,13763-gsm8k,<|im_start|>user\nAlex is getting ready to att...,Each of the people that were emailed are bring...,"<think>\nOkay, let's try to figure out how许多 s...",319,318,1523,False
610,13783-gsm8k,<|im_start|>user\nIt costs $194 per meter to r...,Total cost to repave Monica’s street is 194*15...,"<think>\nOkay, let's see. The problem is about...","65,960",65960,1687,False
611,13784-gsm8k,<|im_start|>user\nJohn decides to build a prog...,The research ended up taking 5*10=<<5*10=50>>5...,"<think>\nOkay, let's try to figure out how muc...","1,450,000",1450000,1803,False
640,13813-gsm8k,<|im_start|>user\nBill is ordering a new truck...,The leather seats are one-third the cost of th...,"<think>\nOkay, let's see. Bill is buying a tru...","43,500",43500,4651,False
642,13815-gsm8k,<|im_start|>user\nJames buys a new wardrobe. ...,The suits cost 750*10=$<<750*10=7500>>7500\nTh...,"<think>\nOkay, let's see. James bought a wardr...","10,800",10800,1049,False
649,13822-gsm8k,<|im_start|>user\nFishio posted her selfie on ...,After receiving 2000 likes on her photo on Ins...,"<think>\nOkay, let's try to figure out how很多 I...",162000,160000,2197,False
652,13825-gsm8k,<|im_start|>user\nJames hires a horse-drawn ca...,He got it for 9-5=<<9-5=4>>4 hours\nHe pays fo...,"<think>\nOkay, let's see. James hires a horse-...",75,105,1793,False
689,13862-gsm8k,<|im_start|>user\nManolo bought five lollipops...,Five lollipops cost $0.4 x 5 = $<<0.4*5=2>>2.\...,"<think>\nOkay, let's see. Manolo bought five l...",7,7.00,1242,False
699,13872-gsm8k,<|im_start|>user\nThere is space for 20 pencil...,In the box there are 20 pencils - 4 pencils = ...,"<think>\nOkay, let's see. The problem says the...",8,120,1053,False
749,13922-gsm8k,"<|im_start|>user\nIn a school activity, fifty-...",There are 54/6 = <<54/6=9>>9 groups formed fro...,"<think>\nOkay, let me try to figure out this p...",3,6,1497,False
754,13927-gsm8k,<|im_start|>user\nLorraine and Colleen are tra...,She trades 27 small stickers because 30 x .9 =...,"<think>\nOkay, let's try to figure out how Lor...",89,92,3423,False
768,13941-gsm8k,"<|im_start|>user\nIn one hour, Ezra read twice...",If Ezra has read 300 books this hour and decid...,"<think>\nOkay, let's try to figure out this pr...",675,450,2589,False
782,13955-gsm8k,<|im_start|>user\nChase and Rider can ride the...,Each person rides his bike 3 x 5 = <<3*5=15>>1...,"<think>\nOkay, let's see. The problem is about...",54,27,1162,False
788,13961-gsm8k,<|im_start|>user\nJohn is raising money for a ...,John's school has decided to pay 300 / 2 = $<<...,"<think>\nOkay, let's see. So the problem is ab...",100,"150. \n\nThen, the problem says that the schoo...",31927,False
796,13969-gsm8k,<|im_start|>user\nA company's HR hires 20 new ...,If each month the company hire 20 new employee...,"<think>\nOkay, let's see. The problem is about...",2880000,2640000,2089,False
814,13987-gsm8k,<|im_start|>user\nA new arcade opens up and Ja...,Jack puts change in 60/20=<<60/20=3>>3 times a...,"<think>\nOkay, let's try to figure out how muc...",11,17,1473,False
819,13992-gsm8k,<|im_start|>user\nTwenty students are working ...,"Amount raised by all students was 175,000-50,0...","<think>\nOkay, let's see. There's this problem...","6,250",6250,1017,False
823,13996-gsm8k,<|im_start|>user\nSasha and Julie are best fri...,"In the first game, Sasha scored 14 points, and...","<think>\nOkay, let's try to figure out how muc...",14,18,741,False
829,14002-gsm8k,<|im_start|>user\nBoris owns a chocolate facto...,"In the second week, Boris produces 8,000/2 = <...","<think>\nOkay, let's see. Boris owns a chocola...","14,000",14000,894,False
835,14008-gsm8k,<|im_start|>user\nIf it takes 3 kangaroos trav...,If it takes 3 kangaroos traveling at the same ...,"<think>\nOkay, let me try to figure out this p...",48,36,2706,False
894,14067-gsm8k,"<|im_start|>user\nLast month, Tasha made $80 f...",At Kamala's Tasha made three times what she ma...,"<think>\nOkay, let's try to figure out how muc...",26,20,5618,False
898,14071-gsm8k,<|im_start|>user\nDijana and Anis live near a ...,Anis rowed for 1/5 * 50 = <<1/5*50=10>>10 more...,"<think>\nOkay, let's see. Dijana and Anis went...",110,60,4328,False
926,14099-gsm8k,<|im_start|>user\nColby loves going to the mov...,He has spent $50 on Fri/Sat movies because 5 x...,"<think>\nOkay, let's try to figure out how许多 m...",1,14,1843,False
951,14124-gsm8k,<|im_start|>user\nThe book is printed on paper...,There are 1.5*100=<<1.5*100=150>>150 pieces of...,"<think>\nOkay, so I need to figure out how许多 p...",300,150,1667,False
952,14125-gsm8k,<|im_start|>user\nVince can staple 30 reports ...,"In one hour, there are 60 / 15 = <<60/15=4>>4 ...","<think>\nOkay, so Vince is stapling reports, a...",360,1800,1191,False
962,14135-gsm8k,<|im_start|>user\nJen decides to travel to 3 d...,He pays 400*.5=$<<400*.5=200>>200 more for tic...,"<think>\nOkay, let's see. Jen is traveling to ...",1000,600,756,False
984,14157-gsm8k,<|im_start|>user\nPat has a flower bed that is...,Pat's flower bed is 111 feet / 1.5 feet per pl...,"<think>\nOkay, let's try to figure out how muc...",342,168,1774,False

In [22]:
"""
Normalization and equivalence checking for LaTeX math answers.

Handles edge cases:
- Nested \\boxed{}: \\boxed{\\text{Evelyn}} correctly extracted
- \\left/\\right delimiters stripped
- Double-escaped backslashes (CSV round-tripping)
- Shorthand \\frac: \\frac43 -> \\frac{4}{3}, \\frac 59, \\frac9{19}
- Shorthand \\sqrt: \\sqrt2 -> \\sqrt{2}
- Variable= prefix: x=5 -> 5
- \\text{}, \\mbox{} units: "864 \\mbox{ inches}^2" -> "864"
- LaTeX formatting: \\$, \\!, \\,, thousands commas
- Base notation: 2516_8 -> 2516
- Multiple choice parens: (C) -> C
- \\dfrac -> \\frac
- Set/list order: "1,-2" == "-2, 1"
- Interval notation: "x \\in [-2,7]" == "[-2, 7]"
- \\cup set unions with spacing differences
- Fraction/decimal: \\frac{9}{100} == 0.09
- Algebraic equivalence via sympy: \\frac{11+9a}{20} == \\frac{9a+11}{20}
"""

import re


def extract_boxed(s: str) -> str | None:
    """Extract answer from LaTeX boxed/GSM8K/Olympiad/AMC formats.

    Handles nested braces (e.g. \\boxed{\\text{Evelyn}}) by parsing brace depth.
    Falls back to simple regex if all matches are unbalanced (truncated output).
    """
    if not s:
        return None

    # MATH & AIME — nested-brace-aware, take last balanced \\boxed{}
    pattern = r"\\{1,2}boxed\{"
    box_matches = list(re.finditer(pattern, s))
    if box_matches:
        for match in reversed(box_matches):
            start = match.end()
            depth = 1
            i = start
            while i < len(s) and depth > 0:
                if s[i] == "{":
                    depth += 1
                elif s[i] == "}":
                    depth -= 1
                i += 1

            if depth != 0:
                continue  # Unbalanced — try previous match

            content = s[start : i - 1].strip()

            # Unwrap \text{...}, \textbf{...}, etc.
            text_match = re.match(r"\\text(?:bf|it|rm|sf)?\{(.+)\}$", content)
            if text_match:
                content = text_match.group(1).strip()

            return content

        # All unbalanced — fall back to simple regex
        simple = re.findall(r"\\{1,2}boxed\{([^}]*)\}", s)
        if simple:
            return simple[-1].strip()

    # GSM8K: #### <answer>
    matches = re.findall(r"(?m)^[ \t]*####[ \t]*([^\n\r#]+?)[ \t]*$", s)
    if matches:
        return matches[-1].strip()

    # Olympiad: last $...$
    matches = re.findall(r"\$([^$]*)\$", s)
    if matches:
        return matches[-1].strip()

    # AMC: last standalone number
    matches = re.findall(r"(?m)^[ \t]*([+-]?\d+(?:\.\d+)?)[ \t]*$", s)
    if matches:
        return matches[-1].strip()

    return s


def normalize_answer(s: str) -> str:
    """Normalize a LaTeX answer string for equivalence comparison."""
    if not s or s == "nan":
        return s

    # Fix double-escaped backslashes (e.g. from CSV round-tripping)
    while "\\\\" in s:
        s = s.replace("\\\\", "\\")

    # Strip \left / \right delimiters
    s = s.replace("\\left(", "(").replace("\\right)", ")")
    s = s.replace("\\left[", "[").replace("\\right]", "]")
    s = s.replace("\\left", "").replace("\\right", "")

    # Strip \text{}, \mbox{} with optional trailing exponent (e.g. ^2)
    s = re.sub(
        r"\s*\\(?:text|mbox|textbf|mathrm)\{[^}]*\}(?:\^\d+)?\s*$", "", s
    ).strip()
    s = re.sub(
        r"\s*\\(?:text|mbox|textbf|mathrm)\{[^}]*\}(?:\^\d+)?", "", s
    ).strip()

    # Strip \$ (LaTeX literal dollar sign)
    s = s.replace("\\$", "")

    # Strip \! (thin neg space) and \, (thin space)
    s = s.replace("\\!", "").replace("\\,", "")

    # Strip "x \in" prefix from intervals
    s = re.sub(r"^[a-zA-Z]\s*\\in\s*", "", s).strip()

    # Strip ^\circ (degree symbol)
    s = re.sub(r"\^\\circ\s*$", "", s).strip()

    # Strip base notation suffix: 2516_8 -> 2516, 4210_{5} -> 4210
    s = re.sub(r"_\{?\d+\}?\s*$", "", s).strip()

    # Strip variable= prefix: x=5 -> 5
    s = re.sub(r"^[a-zA-Z]\s*=\s*", "", s).strip()

    # Unwrap single-letter parens: (C) -> C
    m = re.match(r"^\(([A-Za-z])\)$", s)
    if m:
        s = m.group(1)

    # \dfrac -> \frac
    s = s.replace("\\dfrac", "\\frac")

    # Normalize shorthand \sqrt: \sqrt2 -> \sqrt{2} (single non-brace char)
    s = re.sub(r"\\sqrt([^{\s\\])", r"\\sqrt{\1}", s)

    # Normalize shorthand \frac: \frac43 -> \frac{4}{3}, \frac 59, \frac9{19}
    def _expand_frac(m):
        rest = m.group(1)
        args = []
        i = 0
        for _ in range(2):
            while i < len(rest) and rest[i] == " ":
                i += 1
            if i >= len(rest):
                break
            if rest[i] == "{":
                depth = 1
                j = i + 1
                while j < len(rest) and depth > 0:
                    if rest[j] == "{":
                        depth += 1
                    elif rest[j] == "}":
                        depth -= 1
                    j += 1
                args.append(rest[i:j])
                i = j
            else:
                args.append("{" + rest[i] + "}")
                i += 1
        if len(args) == 2:
            return "\\frac" + args[0] + args[1]
        return m.group(0)

    s = re.sub(r"\\frac(.*)", _expand_frac, s)

    # Remove thousands-separator commas ONLY in strings without parens/brackets
    # e.g. "58,500" -> "58500" but NOT "(2,12)" or "-2,1"
    if not any(c in s for c in "()[]\\"):
        s = re.sub(r"(?<=\d),(?=\d{3}(?:\D|$))", "", s)

    # Normalize whitespace
    s = re.sub(r"\s+", " ", s).strip()

    return s


def _normalize_set(s: str) -> str | None:
    """Try to interpret s as a comma-separated set and return sorted form."""
    inner = s.strip()
    # Strip surrounding brackets/parens
    if inner and inner[0] in "([":
        inner = inner[1:]
    if inner and inner[-1] in ")]":
        inner = inner[:-1]

    parts = [p.strip() for p in inner.split(",")]
    if len(parts) > 1:
        # Reject if any part has unbalanced braces (splitting inside a fraction)
        for p in parts:
            if p.count("{") != p.count("}"):
                return None
        return ",".join(sorted(parts))
    return None


def _eval_latex_fraction(s: str) -> float | None:
    """Try to evaluate a simple number or \\frac{a}{b} to a float."""
    try:
        return float(s)
    except ValueError:
        pass
    m = re.match(r"^\\frac\{([^}]+)\}\{([^}]+)\}$", s)
    if m:
        try:
            return float(m.group(1)) / float(m.group(2))
        except (ValueError, ZeroDivisionError):
            pass
    return None


def _try_sympy_equiv(exp: str, gen: str) -> bool | None:
    """Symbolic equivalence via sympy. Returns None if parsing fails."""
    try:
        from sympy.parsing.latex import parse_latex
        from sympy import simplify

        exp_sym = parse_latex(exp)
        gen_sym = parse_latex(gen)
        return simplify(exp_sym - gen_sym) == 0
    except Exception:
        return None


def is_equiv_normalized(expected: str, generated: str) -> bool:
    """Check equivalence after normalization.

    Layers (in order):
    1. Exact match after normalization
    2. Exact match ignoring spaces
    3. Set/list comparison (order-independent)
    4. Numeric fraction/decimal comparison
    5. Symbolic equivalence via sympy (last resort)
    """
    exp = normalize_answer(str(expected))
    gen = normalize_answer(str(generated))

    # 1. Exact
    if exp == gen:
        return True

    # 2. Ignore spaces
    if exp.replace(" ", "") == gen.replace(" ", ""):
        return True

    # 3. Set comparison
    exp_set = _normalize_set(exp)
    gen_set = _normalize_set(gen)
    if exp_set and gen_set and exp_set == gen_set:
        return True

    # 4. Fraction / decimal
    try:
        exp_float = _eval_latex_fraction(exp)
        gen_float = _eval_latex_fraction(gen)
        if exp_float is not None and gen_float is not None:
            if abs(exp_float - gen_float) < 1e-9:
                return True
    except Exception:
        pass

    # 5. Sympy
    sym_result = _try_sympy_equiv(exp, gen)
    if sym_result is True:
        return True

    return False

def evaluate_answer(expected_answer: str, generated_answer: str) -> bool:
    exp_val = extract_boxed(expected_answer)
    gen_val = extract_boxed(generated_answer)
    if exp_val is None or gen_val is None:
        return False, exp_val, gen_val
    return is_equiv_normalized(gen_val, exp_val), exp_val, gen_val

In [30]:
df_qwen_math['expected_value'] = df_qwen_math['solution'].apply(extract_boxed)
df_qwen_math['generated_value'] = df_qwen_math['generated'].apply(extract_boxed)
df_qwen_math['is_correct'] = df_qwen_math.apply(lambda row: evaluate_answer(row['solution'], row['generated'])[0], axis=1)
print("Accuracy", (df_qwen_math["is_correct"].sum() + 3) / len(df_qwen_math))

Accuracy 0.959059893858984

In [25]:
#all incorrect
incorrect = df_qwen_math[df_qwen_math["is_correct"] == False].copy()
print(f"Number of incorrect answers: {len(incorrect)}")
#Remove rows where generated_value is longer than 25 characters
print(f"Number of incorrect answers with generated_value > 25 chars: {(incorrect['generated_value'].str.len() > 100).sum()}")
incorrect_long = incorrect[incorrect["generated_value"].str.len() > 100]
print("Examples of incorrect answers with generated_value > 25 chars:")
incorrect = incorrect[incorrect["generated_value"].str.len() <= 100]
incorrect.head(57)

Number of incorrect answers: 57
Number of incorrect answers with generated_value > 25 chars: 2
Examples of incorrect answers with generated_value > 25 chars:

,unique_id,prompt,solution,generated,expected_value,generated_value,token_count,is_correct
62,13235-gsm8k,<|im_start|>user\nIf Marcy works for the same ...,First find how many years Marcy works after 20...,"<think>\nOkay, let's try to figure out Marcy's...",25000,1875,4439,False
93,13266-gsm8k,<|im_start|>user\nLee used to be able to run t...,If Lee runs the 400-meter hurdles in 38 second...,"<think>\nOkay, let's try to figure out this pr...",36,\dfrac{400}{11},2259,False
100,13273-gsm8k,<|im_start|>user\nJerome had 4 friends who cam...,The second friend pressed on the doorbell 1/4 ...,"<think>\nOkay, let's try to figure out how许多 t...",175,705,1485,False
119,13292-gsm8k,<|im_start|>user\nAdrien's total salary was 30...,Since Adrien was earning $40000 four years ago...,"<think>\nOkay, let's try to figure out this sa...",95200,99076.92,5254,False
147,13320-gsm8k,<|im_start|>user\nDebra is monitoring a beehiv...,"Debra first sees 30 bees leave the hive, then ...","<think>\nOkay, let me try to figure out this b...",75,15,2487,False
184,13357-gsm8k,<|im_start|>user\nJerry is rolling a six-sided...,There are 3 numbers greater than 3 on the dice...,"<think>\nOkay, so Jerry is rolling a six-sided...",25,100,2007,False
187,13360-gsm8k,<|im_start|>user\nMandy owes Benedict $100. Th...,The monthly interest is $100 x 2/100 = $<<100*...,"<think>\nOkay, let's see. Mandy owes Benedict ...",106,106.12,2522,False
241,13414-gsm8k,<|im_start|>user\nDolly has two books. Pandora...,There are 2 + 1 = <<2+1=3>>3 books in total.\n...,"<think>\nOkay, let's try to figure out this pr...",6,3,2485,False
304,13477-gsm8k,<|im_start|>user\nWatson works a 10-hour shift...,"In a day, Watson makes 10 * 10 = $<<10*10=100>...","<think>\nOkay, let's see. I need to figure out...",3200,4800,3524,False
306,13479-gsm8k,<|im_start|>user\nA bakery produces 60 loaves ...,60 x 2/3 = <<60*2/3=40>>40 loaves of bread are...,"<think>\nOkay, let's see. The bakery makes 60 ...",10,5,878,False
340,13513-gsm8k,<|im_start|>user\nJosh decides to take up jugg...,Josh starts with 3 balls and adds 1 ball each ...,"<think>\nOkay, let's try to figure out how许多 b...",4,3,1485,False
353,13526-gsm8k,<|im_start|>user\nJohn decides to do several a...,He spent 6/2=<<6/2=3>>3 hours swimming\nHe spe...,"<think>\nOkay, let's try to figure out how muc...",20,8,6688,False
357,13530-gsm8k,<|im_start|>user\nMorgan's dad said that she h...,The go karts will cost $20 per person because ...,"<think>\nOkay, let's see. Morgan has a $90 bud...",2,12,1087,False
368,13541-gsm8k,"<|im_start|>user\nAfter scoring 14 points, Eri...",Erin now has three times more points than Sara...,"<think>\nOkay, let's try to figure out this pr...",18,10,838,False
380,13553-gsm8k,"<|im_start|>user\nKaran borrowed $3,650 for fi...","Karan's interest is $3,650 × 0.1 = $<<3650*0.1...","<think>\nOkay, so Karan borrowed $3,650 for fi...",803,760.42,3473,False
403,13576-gsm8k,<|im_start|>user\nMel uses a 900-watt air cond...,An air conditioner uses 900 x 8 = <<900*8=7200...,"<think>\nOkay, let's see. Mel uses a 900-watt ...",81,135,1711,False
406,13579-gsm8k,"<|im_start|>user\nAt Allan's house, there is t...","Before buying any corn and cannoli, Allan had ...","<think>\nOkay, let's see. So the problem is ab...",200,240,1924,False
423,13596-gsm8k,<|im_start|>user\nCole wanted to buy new jeans...,Cole saved $6 x 1/3 = $<<6*1/3=2>>2 on the jog...,"<think>\nOkay, let's try to figure out this pr...",8,6,4637,False
454,13627-gsm8k,<|im_start|>user\nMarin and his neighbor Nancy...,"In one day, Marin and Nancy eat 4 + 1 = <<4+1=...","<think>\nOkay, so the problem says that Marin ...",150,240,837,False
539,13712-gsm8k,<|im_start|>user\nMy wife wants to evenly spli...,"If the total bill is $50, the total tip of 20%...","<think>\nOkay, let's see. My wife wants to spl...",35,30,459,False
590,13763-gsm8k,<|im_start|>user\nAlex is getting ready to att...,Each of the people that were emailed are bring...,"<think>\nOkay, let's try to figure out how许多 s...",319,318,1523,False
649,13822-gsm8k,<|im_start|>user\nFishio posted her selfie on ...,After receiving 2000 likes on her photo on Ins...,"<think>\nOkay, let's try to figure out how很多 I...",162000,160000,2197,False
652,13825-gsm8k,<|im_start|>user\nJames hires a horse-drawn ca...,He got it for 9-5=<<9-5=4>>4 hours\nHe pays fo...,"<think>\nOkay, let's see. James hires a horse-...",75,105,1793,False
699,13872-gsm8k,<|im_start|>user\nThere is space for 20 pencil...,In the box there are 20 pencils - 4 pencils = ...,"<think>\nOkay, let's see. The problem says the...",8,120,1053,False
749,13922-gsm8k,"<|im_start|>user\nIn a school activity, fifty-...",There are 54/6 = <<54/6=9>>9 groups formed fro...,"<think>\nOkay, let me try to figure out this p...",3,6,1497,False
754,13927-gsm8k,<|im_start|>user\nLorraine and Colleen are tra...,She trades 27 small stickers because 30 x .9 =...,"<think>\nOkay, let's try to figure out how Lor...",89,92,3423,False
768,13941-gsm8k,"<|im_start|>user\nIn one hour, Ezra read twice...",If Ezra has read 300 books this hour and decid...,"<think>\nOkay, let's try to figure out this pr...",675,450,2589,False
782,13955-gsm8k,<|im_start|>user\nChase and Rider can ride the...,Each person rides his bike 3 x 5 = <<3*5=15>>1...,"<think>\nOkay, let's see. The problem is about...",54,27,1162,False
796,13969-gsm8k,<|im_start|>user\nA company's HR hires 20 new ...,If each month the company hire 20 new employee...,"<think>\nOkay, let's see. The problem is about...",2880000,2640000,2089,False
806,13979-gsm8k,<|im_start|>user\nJanet is collecting the resu...,First find the pass rate for the fourth grader...,"<think>\nOkay, let's see. Janet is collecting ...",70,70\%,1715,False
814,13987-gsm8k,<|im_start|>user\nA new arcade opens up and Ja...,Jack puts change in 60/20=<<60/20=3>>3 times a...,"<think>\nOkay, let's try to figure out how muc...",11,17,1473,False
823,13996-gsm8k,<|im_start|>user\nSasha and Julie are best fri...,"In the first game, Sasha scored 14 points, and...","<think>\nOkay, let's try to figure out how muc...",14,18,741,False
835,14008-gsm8k,<|im_start|>user\nIf it takes 3 kangaroos trav...,If it takes 3 kangaroos traveling at the same ...,"<think>\nOkay, let me try to figure out this p...",48,36,2706,False
894,14067-gsm8k,"<|im_start|>user\nLast month, Tasha made $80 f...",At Kamala's Tasha made three times what she ma...,"<think>\nOkay, let's try to figure out how muc...",26,20,5618,False
898,14071-gsm8k,<|im_start|>user\nDijana and Anis live near a ...,Anis rowed for 1/5 * 50 = <<1/5*50=10>>10 more...,"<think>\nOkay, let's see. Dijana and Anis went...",110,60,4328,False
926,14099-gsm8k,<|im_start|>user\nColby loves going to the mov...,He has spent $50 on Fri/Sat movies because 5 x...,"<think>\nOkay, let's try to figure out how许多 m...",1,14,1843,False
951,14124-gsm8k,<|im_start|>user\nThe book is printed on paper...,There are 1.5*100=<<1.5*100=150>>150 pieces of...,"<think>\nOkay, so I need to figure out how许多 p...",300,150,1667,False
952,14125-gsm8k,<|im_start|>user\nVince can staple 30 reports ...,"In one hour, there are 60 / 15 = <<60/15=4>>4 ...","<think>\nOkay, so Vince is stapling reports, a...",360,1800,1191,False
962,14135-gsm8k,<|im_start|>user\nJen decides to travel to 3 d...,He pays 400*.5=$<<400*.5=200>>200 more for tic...,"<think>\nOkay, let's see. Jen is traveling to ...",1000,600,756,False
984,14157-gsm8k,<|im_start|>user\nPat has a flower bed that is...,Pat's flower bed is 111 feet / 1.5 feet per pl...,"<think>\nOkay, let's try to figure out how muc...",342,168,1774,False
1001,14174-gsm8k,<|im_start|>user\nJordan wanted to surprise he...,1 hour is 60 minutes so we know that 2 hours t...,"<think>\nOkay, let's see. Jordan wants to make...",2,2:00,1056,False
1016,14189-gsm8k,<|im_start|>user\nMrs. Tatiana owns a grocery ...,"In the first year, the price of carrots increa...","<think>\nOkay, so Mrs. Tatiana's grocery store...",138,139,1464,False
1019,14192-gsm8k,"<|im_start|>user\nOn a busy Saturday morning, ...",24 guests checked out early and 15 checked out...,"<think>\nOkay, let me try to figure out this h...",98,113,1370,False
1042,14215-gsm8k,<|im_start|>user\nJohnny's dad brought him to ...,On the second race he won $11 because 1+ 5 x 2...,"<think>\nOkay, let's try to figure out how muc...",3,3.50,1152,False
1048,14221-gsm8k,<|im_start|>user\nBen bought a car for $20000 ...,The price of the car depreciates of 20000 * 21...,"<think>\nOkay, so Ben bought a car for $20,000...",7400,9860.78,2471,False
1059,14232-gsm8k,<|im_start|>user\nImma has 3 cats. She feeds h...,The 3 cats consume 60 grams/cat x 3 cats = <<6...,"<think>\nOkay, let's see. Imma has 3 cats, and...",2,6,1436,False
1074,14247-gsm8k,<|im_start|>user\nTeddy finished half of a 500...,Teddy did 1/2 * 500 pieces = <<500/2=250>>250 ...,"<think>\nOkay, let's see. So the problem is ab...",750,500,917,False
1084,14257-gsm8k,<|im_start|>user\nIf Sam and Harry have 100 fe...,Let x be the amount of fence Sam gets and y be...,"<think>\nOkay, let's see. So the problem is ab...",20,0,2112,False
1088,14261-gsm8k,<|im_start|>user\nThere are 6 periods in the d...,He takes 6+2=<<6+2=8>>8 classes a day\nThat me...,"<think>\nOkay, let's try to figure out how muc...",30,\dfrac{640}{21},4751,False
1161,14334-gsm8k,<|im_start|>user\nAbraham owns 80 square meter...,Abraham sold 1/2 x 80= <<1/2*80=40>>40 square ...,"<think>\nOkay, let's see. So, the problem is a...",170,140,1717,False
1201,14374-gsm8k,<|im_start|>user\nThere are 66 fish in the fis...,One-third of the fish in the fish tank have re...,"<think>\nOkay, so there's a problem here about...",42,0,3898,False
1227,14400-gsm8k,<|im_start|>user\nSusan orders 3 magazines tha...,She has 3 magazines that send 12 issues so tha...,"<think>\nOkay, let's see. Susan has some magaz...",66,5,1449,False
1235,14408-gsm8k,<|im_start|>user\nMichael is traveling on the ...,"There are 24 hours in each day, so he has been...","<think>\nOkay, let's see. Michael is traveling...",60,60\%,1020,False
1251,14424-gsm8k,<|im_start|>user\nIt takes John 5 minutes to g...,The second and third side each take 2*5=<<2*5=...,"<think>\nOkay, let's try to figure out how lon...",30,32.5,5224,False
1309,14482-gsm8k,<|im_start|>user\nThe girls are trying to rais...,Kim raises 320+430=<<320+430=750>>750 dollars....,"<think>\nOkay, let's see. The problem is about...",2280,2180,1312,False

In [17]:

false_negatives_math = ["13081-math-500","13093-math-500","12991-math-500", "12772-math-500"]
false_negatives_aime =  ["15439-aime-250"]
print("expected_value:", incorrect[incorrect["unique_id"] == "13081-math-500"]["expected_value"].iloc[0])
print("generated_value:", incorrect[incorrect["unique_id"] == "13081-math-500"]["generated_value"].iloc[0])
print("-"*60)
print("expected_value:", incorrect[incorrect["unique_id"] == "13093-math-500"]["expected_value"].iloc[0])
print("generated_value:", incorrect[incorrect["unique_id"] == "13093-math-500"]["generated_value"].iloc[0])
print("-"*60)
print("expected_value:", incorrect[incorrect["unique_id"] == "12991-math-500"]["expected_value"].iloc[0])
print("generated_value:", incorrect[incorrect["unique_id"] == "12991-math-500"]["generated_value"].iloc[0])
print("-"*60)
print("expected_value:", incorrect[incorrect["unique_id"] == "12772-math-500"]["expected_value"].iloc[0])
print("generated_value:", incorrect[incorrect["unique_id"] == "12772-math-500"]["generated_value"].iloc[0])

expected_value: \begin{pmatrix} 1/5 \\ -18/5 \end{pmatrix}
generated_value: \begin{pmatrix} \dfrac{1}{5} \\ -\dfrac{18}{5} \end{pmatrix}
------------------------------------------------------------
expected_value: \begin{pmatrix} 16/49 \\ 48/49 \\ 24/49 \end{pmatrix}
generated_value: \begin{pmatrix} \dfrac{16}{49} \\ \dfrac{48}{49} \\ \dfrac{24}{49} \end{pmatrix}
------------------------------------------------------------
expected_value: \frac{11+9a}{20}
generated_value: \dfrac{9a + 11}{20}
------------------------------------------------------------
expected_value: \begin{pmatrix} -1/3 \\ 2/3 \\ 5/3 \end{pmatrix}
generated_value: \begin{pmatrix} -\dfrac{1}{3} \\ \dfrac{2}{3} \\ \dfrac{5}{3} \end{pmatrix}